Repository CSC207-2022F-UofT/course-project-team-tree-dog, pull requests merged in 2022-11, with the labels that each got.

#36 13 use case pull data
  src/main/java/usecases/pull_data/PdInputBoundary.java
  src/main/java/usecases/pull_data/PdInputData.java
  src/main/java/usecases/pull_data/PdInteractor.java
  src/main/java/usecases/pull_data/PdOutputBoundary.java
  src/main/java/usecases/pull_data/PdOutputData.java
Labels: feature

#46 32 unit test pull data interactor
  src/test/java/usecases/pull_data/PdInteractorTests.java
Labels: Test

#47 Add simple tests for join public lobby use case
  src/main/java/entities/PlayerFactory.java
  src/test/java/usecases/join_public_lobby/JoinPublicLobbyTest.java
  src/test/java/usecases/pull_data/PdInteractorTests.java
Labels: Test

#52 Finish refactoring ResponseTest
  src/main/java/usecases/Response.java
  src/test/java/entities/ResponseTest.java
Labels: Refactoring

#68 44 misc thread safety use case architecture
  src/main/java/entities/LobbyManager.java
  src/main/java/entities/PlayerPoolListener.java
  src/main/java/entities/games/GameRegular.java
  src/main/java/usecases/disconnecting/DcInteractor.java
  src/main/java/usecases/join_public_lobby/JplInteractor.java
  src/main/java/usecases/run_game/RgInteractor.java
  src/main/java/usecases/sort_players/SpInteractor.java
  src/main/java/usecases/submit_word/SwInteractor.java
  src/main/java/usecases/submit_word/SwOutputDataFailure.java
  src/main/java/usecases/submit_word/SwOutputDataValidWord.java
  src/test/java/usecases/disconnecting/DcInteractorTests.java
  src/test/java/usecases/join_public_lobby/JoinPublicLobbyTest.java
  src/test/java/usecases/pull_data/PdInteractorTests.java
  src/test/java/usecases/run_game/RgTaskTests.java
  src/test/java/usecases/sort_players/SpInteractorTests.java
  src/test/java/usecases/submit_word/SwInteractorTests.java
Labels: Concurrency

#73 64 use case like story
  src/main/java/usecases/like_story/LsGateway.java
  src/main/java/usecases/like_story/LsGatewayInputData.java
  src/main/java/usecases/like_story/LsGatewayOutputData.java
  src/main/java/usecases/like_story/LsInputBoundary.java
  src/main/java/usecases/like_story/LsInputData.java
  src/main/java/usecases/like_story/LsInteractor.java
  src/main/java/usecases/like_story/LsOutputBoundary.java
  src/main/java/usecases/like_story/LsOutputData.java
  src/test/java/usecases/like_story/LsTests.java
Labels: feature
